- name: Provision
  hosts: all

  tasks:
    - name: Reduce unprivileged port start
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        value: "80"

    - name: Manage Podman APT key
      become: true
      ansible.builtin.apt_key:
        url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ ansible_distribution_version }}/Release.key"

    - name: Manage Podman APT repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ ansible_distribution_version }}/ /"

    - name: Manage Podman APT package
      become: true
      ansible.builtin.apt:
        pkg: podman

    - name: Manage socket activation of Podman API service
      ansible.builtin.systemd:
        enabled: true
        name: podman.socket
        scope: user
        state: started

    - name: Link Docker to Podman
      become: true
      ansible.builtin.file:
        dest: /usr/local/bin/docker
        src: /usr/bin/podman
        state: link
