Vagrant.configure("2") do |configuration|
  configuration.vm.box = "ubuntu/jammy64"
  configuration.vm.network "private_network", ip: ENV["WHEELSTICKS_VM_IP_ADDRESS"]
  configuration.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end
