name = "my_project"

[services]

[services.my_service_0]
build = "my_build_context_0"
profiles = ["debug", "test"]
x-example = "extension"

[services.my_service_1]
build = "my_build_context_1"
unknown = "foo"

[x-custom]
foo = ["bar"]

[x-wheelsticks]
local_workbench = "my_local_workbench"
remote_workbench = "my_remote_workbench"
schema_mode = "loose"
user_systemd_folder = "my_user_systemd_folder"
