name: my_project
services:
  my_service_0:
    build: my_build_context_0
    unknown: foo
    x-example: extension
  my_service_1:
    build: my_build_context_1
    unsupported: bar
x-custom:
  foo:
    - bar
x-wheelsticks:
  local_workbench: my_local_workbench
  remote_workbench: my_remote_workbench
  schema_mode: loose
