[package]
name = "wheelsticks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = [
  "derive",
  "error-context",
  "help",
  "usage",
  "wrap_help"
] }
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tempfile = "3.3"
test-case = "2.2"
wait-timeout = "0.2"
