[package]
name = "wheelsticks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "4.1", features = [
  "color",
  "derive",
  "error-context",
  "help",
  "std",
  "suggestions",
  "usage",
  "wrap_help"
] }
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
serde_yaml = "0.9"
toml = "0.7"
tempfile = "3.3"
test-case = "2.2"
wait-timeout = "0.2"
