Vagrant.configure("2") do |configuration|
  configuration.vm.box = "ubuntu/jammy64"
  configuration.vm.network "private_network", ip: "192.168.60.159"
  configuration.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = "2048"
  end
end
