name: example
services:
  greet:
    command: "caddy respond --listen :80 'Hi from ${GREET_VERSION-A}\n'"
    deploy:
      update_config:
        order: start-first
    image: "docker.io/caddy:2-alpine"

  reverse-proxy:
    command: caddy reverse-proxy --from :81 --to greet
    image: "docker.io/caddy:2-alpine"
    ports:
      - "127.0.0.1:8080:81"
