Vagrant.configure("2") do |configuration|
  configuration.vm.box = "bento/ubuntu-24.04"
  configuration.vm.define "kerek_example_production"
  configuration.vm.network "private_network", ip: "192.168.60.159"
end
