services:
  web-no-build:
    command: ["-text=Hi from 8080"]
    image: docker.io/hashicorp/http-echo:1.0
    ports:
      - "8080:5678"
  web-with-build:
    build: .
    ports:
      - "8181:5678"
