permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Update-worthy.
      - uses: taiki-e/create-gh-release-action@v1 # Update-worthy.
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload_assets:
    needs: create_release
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4 # Update-worthy.
      - uses: taiki-e/upload-rust-binary-action@v1 # Update-worthy.
        with:
          bin: kerek
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
